### ISSUE TITLE
Missing release after name change

### ISSUE THREAD

**Issue by nicolasferraro** [phenixdigital/phoenix_storybook#241]
Hey! I'm looking into adding this library into our project and noticed that it's name has changed (like 3 hours ago). I followed the installation steps listed on the Readme but I ran into an issue when fetching the dependency:

```shell
> mix deps.get
Failed to fetch record for phoenix_storybook from registry (using cache instead)
This could be because the package does not exist, it was spelled incorrectly or you don't have permissions to it
** (Mix) No package with name phoenix_storybook (from: mix.exs) in registry
```

I've looked for the package in Hex and it doesn't seem to be there, I think you need to make a new release so it picks up the new name?

Thanks!

**Comment by cblavier** [comment]
Hey Nicolas, a new release is due today! Stay tuned :)

**Comment by cblavier** [comment]
Ok this is awkward, but I'll have to postpone the release a bit:
- because right now `phoenix_storybook` depends on `phoenix 1.7.0-rc.2` and `phoenix_live_view 0.18.3`
- but `phoenix_live_view 0.18.3` depends on `phoenix 1.7` (not yet released) and not on the rc.2 

This is working on the main branch, because of an `override` flag but I can't release it with an `override` flag in deps.

I just asked the Phoenix core team, `Phoenix 1.7.0` is around the corner (should be released next week), so in the meantime I'll ask you to either use:
- `{:phx_live_storybook, "0.4.5"}`
- or `{:phoenix_storybook, github: "phenixdigital/phoenix_storybook"}`

I'll amend the `README` right away

**Comment by nicolasferraro** [comment]
Thanks for the update! I think we'll end up using the older version for now and then update when the new release is cut

**Comment by cblavier** [comment]
0.5.0 has just been released 🚀
