### ISSUE TITLE
add `../storybook/**/*.exs` to tailwind.config.js content path

### ISSUE THREAD

**Issue by tcoopman** [phenixdigital/phoenix_storybook#249]
Otherwise the classes you use in your storybooks are not picked up by tailwind.
I'm not sure this is great though, because it can increase the size of your overall css. But I'm also not sure if there is a good way to solve this?

**Comment by cblavier** [comment]
There is nothing much to do in order to fix this issue: the `content` path that should be amended is not in the storybook's `tailwind.config` but in the application's config.

You can look at the `phoenix_storybook_sample` repository and its button story.
If you run it locally and update the class attribute, tailwind's JIT kicks in as needed.
