### ISSUE TITLE
add the option to only add and build storybook in development

### ISSUE THREAD

**Issue by tcoopman** [phenixdigital/phoenix_storybook#250]
see discussion here: https://elixirforum.com/t/phoenix-storybook-a-storybook-like-ui-interface-for-phoenix-components/48890/52?u=tcoopman

For me the reason is that I want to use storybook for a project  that is not open source and doesn't share it's components. Here storybook is still a great way of showing all the possible components and creating a great style guide.

**Comment by tcoopman** [comment]
I'll try to have a look at it sooner than in 6 months 😂

The router trick I'm already using but the lazy compiling looks useful. I'll try it out!

**Comment by cblavier** [comment]
ok, I just set myself a reminder to come back here by April 10, 2024

**Comment by neilberkman** [comment]
Just a 👍 for this (timely since your reminder date is in 5 days). Storybook compilation adds about 1 minute to all of our CI runs, and as this is just wasted time and expense we'd love to have a way to avoid this. Thanks.

**Comment by crova** [comment]
To echo on @neilberkman 's comment, we tried the suggested steps and `compilation_mode: :lazy` helps in cutting the number of compiled assets.
However, as the doc states, we still compile `.index.exs`, ideally we wouldn't.

In our case, we partition test, so for instance, we're compiling this file 4 times for each PR.

I think we want to be able to [not start](https://github.com/phenixdigital/phoenix_storybook/blob/a140cca3824a120247b0681986c66e0e51bb7918/lib/phoenix_storybook/application.ex#L14) the compiler in some environments?

**Comment by cblavier** [comment]
The people has spoken!
I'll have a look next week ;-)

**Comment by Gladear** [comment]
Hi ! I had the same problem (not because my project isn't open-source, but because I didn't want to use resources in my prod env with the storybook) and I think I figured out a solution 😄

- hide the routes behind any kind of dev flag. I used `:dev_routes`, the one generated by Phoenix for LiveDashboard and Swoosh mailbox, but `if Mix.env() == :dev do` does the trick too 😄 This ensures the route is only available in dev and the app's Storybook module won't be called.
- add `runtime: Mix.env() == :dev` to the dependency in mix.exs. This removes `:phoenix_storybook` from applications started at startup in non-dev environment, ensuring it doesn't take any runtime resource.
```exs
{:phoenix_storybook, "~> 0.6.3", runtime: Mix.env() == :dev},
```
- add `compilation_mode: :lazy` to the Storybook module - not necessary, but avoids non-necessary compilation of files.

If you need more details, this was implemented in this PR: https://github.com/anacounts/app/pull/221

**Comment by cblavier** [comment]
Thanks a lot, @Gladear!
If it does the trick for other folks involved, I'll close the issue.

**Comment by crova** [comment]
Just to chime in from our perspective, we ended up using a macro to avoid compiling any storybook related code in non-dev env.
As I understood the great suggestion by @Gladear , it reduces the compile/runtime penalty to almost zero, but there is still some cost (e.g.: .index.exs will always be compiled).

As we see it, the ideal solution would come from the library itself. But we totally respect the decision of the maintainer on this subject if @cblavier decides to keep things as they are.

**Comment by cblavier** [comment]
@crova I agree that the library should provide a way to disable itself in some env.
I have no time right now: would you mind opening a PR?

**Comment by cblavier** [comment]
Please let me know how it's working for you guys!

**Comment by crova** [comment]
@cblavier First things first, thank you very much for the work on this.
Sorry I never got back to you on this subject, I totally missed your reply (and to be honest I don't think I would've been able to help much on this).
I'm not sure if we're going to give this a try right away as we've got quite a few priorities on our backlog and we do have a working solution for now.
But I'll make a note to give you a feedback if/when we give this a spin.

Again, thank you very much for the great library and this update.
