### ISSUE TITLE
Render documentation more like ExDocs?

### ISSUE THREAD

**Issue by gaggle** [phenixdigital/phoenix_storybook#486]
Pulling module- and function-docs is a great touch! The text comes out quite plain though, would you consider a way to render it via Markdown? We have lots of expressive Markdown'd docs because ExDocs picks up on that, would be great to see that reflected in Storybook pages.

Or, perhaps a callback that can be specified in `use PhoenixStorybook` so I can wire in a Markdown library if you don't want to get include on directly w. the library? (though IMHO it'd be unsurprising for Storybook to render Markdown, as that's what we're used to from ExDocs, but I recognize there are tradeoffs to supporting such a feature)

Anyway, great library, thanks for making it!

**Comment by gaggle** [comment]
Wait, now I do see Markdown formatting? I could've sworn that wasn't showing up before... 

Perhaps I can then use this issue to ask if you'd consider also showing @moduledoc content? Or perhaps simply link to ExDocs, if I specify something like an ExDocs path in Phoenix Storybook's configuration?

**Comment by cblavier** [comment]
Since a single module can host multiple function components (like `core_components.ex`) we only pull @doc attribute for a function component. For `live_component`, we fetch `@moduledoc` content

Linking to `https://hexdocs.pm/` can be a good idea, but I'll need you to open a PR :)
It should be configurable with a new `hexdocs_url` option in `storybook.ex`

Then for each story (function or module based story) you can infer the module path and add an hexdocs.pm link in the story page header

**Comment by cblavier** [comment]
hey @gaggle 
is it ok for you? can we close the issue?

**Comment by gaggle** [comment]
Oh sorry, yes thank you!
